version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql    
    env_file:
      - ./.env
    networks:
      - inception
    restart: always

  wordpress:
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    container_name: wordpress
    ports: 
      - "9000:9000"
    volumes:
      - wp_files:/var/www/html
    env_file:
      - ./.env
    networks:
      - inception
    restart: always
      
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wp_files:/var/www/html
    networks:
      - inception
    restart: always

volumes:
  db_data:
  wp_files:

networks:
  inception:
    driver: bridge
