version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wp_files:/var/www/html
    networks:
      - inception
    restart: always
    depends_on:
      - wordpress

  wordpress:
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wp_files:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - DOMAIN_NAME=${DOMAIN_NAME}                
      - WP_ADMIN_USER=${WP_ADMIN_USER}            
      - WP_ADMIN_PASS=${WP_ADMIN_PASS}            
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
    networks:
      - inception
    restart: always

  mariadb:
    build: ./requirements/mariadb
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - inception
    restart: always

volumes:
  db_data:
  wp_files:

networks:
  inception:
    driver: bridge